### ISSUE TITLE
java.lang.IllegalStateException: Saves user failed 	at org.b3log.latke.demo.service.UserService.saveUser(UserService.java:41)

### ISSUE THREAD

**Issue by liudongdong1** [b3log/latke-demo#5]
i modify the local.properties,runtimeDatabase=H2

#### JDBC database Configurations ####
jdbc.driver=org.h2.Driver
jdbc.URL=jdbc:h2:~/quickstart
jdbc.username=
jdbc.password=
but i get an error when run the demo,
@Service
public class UserService {

    private static final Logger LOGGER = Logger.getLogger(UserService.class);

    @Inject        // @Inject 注入需要的服务：
    private UserRepository userRepository;

    @Transactional
    public void saveUser(final String name, final int age) {
        final JSONObject user = new JSONObject();
        user.put("name", name);
        user.put("age", age);

        String userId;

        try {
            userId = userRepository.add(user);
        } catch (final RepositoryException e) {
            LOGGER.log(Level.ERROR, "Saves user failed", e);

            // Throws an exception to rollback transaction
            throw new IllegalStateException("Saves user failed");
        }

        LOGGER.log(Level.INFO, "Saves a user successfully [userId={0}]", userId);
    }
}

org.b3log.latke.repository.RepositoryException: Invoking add() outside a transaction
	at org.b3log.latke.repository.jdbc.JdbcRepository.add(JdbcRepository.java:137)
	at org.b3log.latke.repository.AbstractRepository.add(AbstractRepository.java:110)
	at org.b3log.latke.demo.service.UserService.saveUser(UserService.java:36)
	at org.b3log.latke.demo.processor.RegisterProcessor.register(RegisterProcessor.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.servlet.handler.MethodInvokeHandler.handle(MethodInvokeHandler.java:55)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:97)
	at org.b3log.latke.servlet.handler.AdviceHandler.handle(AdviceHandler.java:104)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:97)
	at org.b3log.latke.servlet.handler.ArgsHandler.handle(ArgsHandler.java:59)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:97)
	at org.b3log.latke.servlet.handler.RequestDispatchHandler.handle(RequestDispatchHandler.java:86)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:97)
	at org.b3log.latke.servlet.handler.RequestPrepareHandler.handle(RequestPrepareHandler.java:43)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:97)
	at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticResourceHandler.java:119)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:97)
	at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:76)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:651)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:417)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1376)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.servlet.handler.MethodInvokeHandler.handle(MethodInvokeHandler.java:55)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:97)
	at org.b3log.latke.servlet.handler.AdviceHandler.handle(AdviceHandler.java:104)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:97)
	at org.b3log.latke.servlet.handler.ArgsHandler.handle(ArgsHandler.java:59)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:97)
	at org.b3log.latke.servlet.handler.RequestDispatchHandler.handle(RequestDispatchHandler.java:86)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:97)
	at org.b3log.latke.servlet.handler.RequestPrepareHandler.handle(RequestPrepareHandler.java:43)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:97)
	at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticResourceHandler.java:119)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:97)
	at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:76)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:651)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:417)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1376)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Saves user failed
	at org.b3log.latke.demo.service.UserService.saveUser(UserService.java:41)
	at org.b3log.latke.demo.processor.RegisterProcessor.register(RegisterProcessor.java:39)
	... 40 more
![image](https://user-images.githubusercontent.com/25970295/48965310-8740d880-eff5-11e8-9e32-b3effb399293.png)
and i don't know how to fix?Thanks for your time!

**Comment by 88250** [comment]
你好，改 H2 的存储路径不影响，我这里试过了。但是你说的问题我没能重现，你仔细看下日志。另外，确认一下是不是改过其他地方。
